include $(AMF_PROJECT_MK_ROOT)/rule.mk
TARGET_TYPE=lib
TARGET_NAME=libnl_socket.a
LIBEVENT_PATH=$(AMF_PROJECT_ROOT)/src/lib/libevent
INCLUDE_PATH += -I$(AMF_PROJECT_ROOT)/src/ \
	-I$(LIBEVENT_PATH)/include
include $(AMF_PROJECT_MK_ROOT)/basic.mk

