include $(AMF_PROJECT_MK_ROOT)/rule.mk

#MODULE_BEFORE=before
#MODULE_AFTER=end

#before:
#	@echo "do something before make"

#end:
#	@echo "do something after make"

TARGET_TYPE=
SUB_MODULE=kportal
INCLUDE_PATH+=
include $(AMF_PROJECT_MK_ROOT)/basic.mk

